#[build-system]
#requires = ["flit_core >=3.2,<4"]
#build-backend = "flit_core.buildapi"

[project]
name = "pyfin"
authors = [{ name = "Lachlan Marnoch", email = "lachlan.marnoch@gmail.com" }]
version = "0.1"
requires-python = ">=3.11"
dependencies = [
    "astropy",
    "numpy",
]
license = { file = "LICENSE.md" }
description = "."
readme = "README.md"
[project.scripts]
new_etf_product = "pyfin.bin.new_etf_product:parse_args"
new_portfolio = "pyfin.bin.new_portfolio:parse_args"
run_sim = "pyfin.bin.run_sim:parse_args"
